import {useState} from 'react';
import {Activity,AlertTriangle,Bell,Bug,ChevronRight,Command,GitBranch,LayoutDashboard,Menu,Radio,Settings2,ShieldCheck, X} from 'lucide-react';
import {Link,NavLink,useLocation} from 'react-router-dom';
import {formatDate,useApi,type RateLimit} from './api';

const navigation=[{to:'/',label:'Overview',icon:LayoutDashboard,end:true},{to:'/activity',label:'Activity',icon:Activity},{to:'/programs/immunefi',label:'Immunefi',icon:ShieldCheck},{to:'/programs/hackenproof',label:'HackenProof',icon:ShieldCheck},{to:'/programs/other',label:'Other programs',icon:ShieldCheck},{to:'/repositories',label:'Repositories',icon:GitBranch},{to:'/vulnerabilities',label:'Vulnerabilities',icon:Bug}];
const titles:Record<string,string>={'/':'Overview','/activity':'Activity','/programs':'Programs','/programs/immunefi':'Immunefi programs','/programs/hackenproof':'HackenProof programs','/programs/other':'Other programs','/repositories':'Repositories','/vulnerabilities':'Vulnerabilities','/settings':'Settings'};
function RateLimitBanner(){const {data}=useApi<RateLimit|null>('/github/rate-limit',30000);if(!data||new Date(data.reset_at).getTime()<=Date.now())return null;return <div className="rate-limit-banner" role="status"><AlertTriangle size={18}/><div><strong>GitHub rate limit reached</strong><span>Release, repository and source scans stopped at {formatDate(data.hit_at)}. GitHub allows requests again at {new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(data.reset_at))}.</span></div></div>}
export function Layout({children}:{children:React.ReactNode}){const [open,setOpen]=useState(false);const location=useLocation();const section=Object.keys(titles).filter(path=>path==='/'?location.pathname==='/':location.pathname.startsWith(path)).sort((a,b)=>b.length-a.length)[0]||'/';return <div className="app-shell"><div className={'mobile-shade '+(open?'visible':'')} onClick={()=>setOpen(false)}/><aside className={'sidebar '+(open?'sidebar-open':'')}><div className="brand"><div className="brand-mark"><Radio size={22}/></div><div><strong>Signalbase</strong><small>BOUNTY INTELLIGENCE</small></div><button className="mobile-close" onClick={()=>setOpen(false)} aria-label="Close navigation"><X size={20}/></button></div><div className="sidebar-section-label">WORKSPACE</div><nav className="side-nav">{navigation.map(item=><NavLink key={item.to} to={item.to} end={item.end} onClick={()=>setOpen(false)} className={({isActive})=>'nav-link '+(isActive?'nav-active':'')}><item.icon size={18}/><span>{item.label}</span>{item.to==='/activity'&&<span className="nav-dot"/>}</NavLink>)}</nav><div className="sidebar-bottom"><div className="sidebar-section-label">PREFERENCES</div><NavLink to="/settings" onClick={()=>setOpen(false)} className={({isActive})=>'nav-link '+(isActive?'nav-active':'')}><Settings2 size={18}/><span>Settings</span></NavLink><div className="sidebar-status"><span className="status-light"/><div><strong>Local workspace</strong><small>Private deployment</small></div></div></div></aside><div className="workspace"><header className="topbar"><div className="topbar-left"><button className="menu-toggle" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu size={21}/></button><span className="topbar-crumb">Workspace</span><ChevronRight size={15}/><strong>{titles[section]}</strong></div><div className="topbar-right"><span className="topbar-date">{new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric'}).format(new Date())}</span><Link className="topbar-action" to="/activity" title="View activity"><Bell size={18}/></Link><Link className="topbar-avatar" to="/settings" title="Settings"><Command size={18}/></Link></div></header><main className="content"><RateLimitBanner/>{children}</main><footer className="app-footer"><span>Signalbase · Local bounty intelligence</span><span>Built for focused research</span></footer></div></div>}
