import type {ReactNode} from 'react';
import {ArrowRight, Check, Inbox, LoaderCircle} from 'lucide-react';
import {Link} from 'react-router-dom';
import type {Event} from './api';
import {eventDescription,eventLabel,relativeDate} from './api';

export function PageTitle({eyebrow,title,description,action}:{eyebrow:string;title:string;description?:string;action?:ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action&&<div className="heading-actions">{action}</div>}</div>}
export function Panel({title,subtitle,action,children,className=''}:{title?:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={'panel '+className}>{(title||action)&&<div className="panel-heading"><div>{title&&<h2>{title}</h2>}{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}{children}</section>}
export function Empty({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className="empty"><div className="empty-icon"><Inbox size={22}/></div><h3>{title}</h3>{description&&<p>{description}</p>}{action&&<div className="empty-action">{action}</div>}</div>}
export function Loading(){return <div className="loading"><LoaderCircle className="spin" size={20}/> Loading your data...</div>}
export function ErrorBanner({message}:{message:string}){return <div className="error-banner">{message}</div>}
export function ButtonLink({to,children,secondary=false}:{to:string;children:ReactNode;secondary?:boolean}){return <Link className={'button '+(secondary?'button-secondary':'button-primary')} to={to}>{children}</Link>}
export function TextLink({to,children}:{to:string;children:ReactNode}){return <Link className="text-link" to={to}>{children}<ArrowRight size={15}/></Link>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'green'|'blue'|'amber'|'red'|'purple'}){return <span className={'badge badge-'+tone}>{children}</span>}
export function Pagination({total,offset,setOffset,limit=25}:{total:number;offset:number;setOffset:(offset:number)=>void;limit?:number}){if(total<=limit)return null;return <div className="pagination"><span>Showing {offset+1}–{Math.min(offset+limit,total)} of {total}</span><div><button className="button button-secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-limit))}>Previous</button><button className="button button-secondary" disabled={offset+limit>=total} onClick={()=>setOffset(offset+limit)}>Next</button></div></div>}
const eventTone:Record<string,'green'|'blue'|'amber'|'purple'|'neutral'>={NEW_RELEASE:'green',NEW_TAG:'purple',NEW_PROGRAM:'blue',NEW_REPOSITORY:'blue',SCOPE_ADDED:'green',SCOPE_REMOVED:'amber',NEW_COMMIT:'neutral'};
export function EventRow({event,onMarkRead}:{event:Event;onMarkRead?:(id:number)=>void}){return <div className={'activity-row '+(!event.read_at?'activity-unread':'')}><div className={'activity-marker marker-'+(eventTone[event.event_type]||'neutral')}/><div className="activity-body"><div className="activity-main"><Badge tone={eventTone[event.event_type]||'neutral'}>{eventLabel(event.event_type)}</Badge><span className="activity-time">{relativeDate(event.created_at)}</span></div><div className="activity-description">{eventDescription(event)}</div><div className="activity-context">{event.repository_name&&<Link to={'/repositories/'+event.repository_id}>{event.repository_name}</Link>}{event.program_name&&<Link to={'/programs/'+event.program_id}>{event.program_name}</Link>}</div></div>{onMarkRead&&!event.read_at&&<button className="mark-read" onClick={()=>onMarkRead(event.id)} title="Mark as read" aria-label="Mark event as read"><Check size={15}/></button>}</div>}
